/* Generated By:JJTree: Do not edit this line. ASTAGENUM.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAGENUM extends SimpleNode {
  public ASTAGENUM(int id) {
    super(id);
  }

  public ASTAGENUM(Parse_xml p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Parse_xmlVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1c931cd858f1a8af88642c09a70483a5 (do not edit this line) */
