/* Generated By:JJTree: Do not edit this line. ASTCLOSENTAG.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCLOSENTAG extends SimpleNode {
  public ASTCLOSENTAG(int id) {
    super(id);
  }

  public ASTCLOSENTAG(Parse_xml p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Parse_xmlVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ed05593bc9f18d4e613cb9590e185c8c (do not edit this line) */
