/* Generated By:JJTree: Do not edit this line. ASTCLOSTAGATTR.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCLOSTAGATTR extends SimpleNode {
  public ASTCLOSTAGATTR(int id) {
    super(id);
  }

  public ASTCLOSTAGATTR(Parse_xml p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Parse_xmlVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f62d52b862c2257b60b0c20fbd9d136f (do not edit this line) */
