/* Generated By:JJTree: Do not edit this line. ASTIDNUM.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIDNUM extends SimpleNode {
  public ASTIDNUM(int id) {
    super(id);
  }

  public ASTIDNUM(Parse_xml p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Parse_xmlVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=11454d373d8b9677eda2cabd77002d5f (do not edit this line) */
