/* Generated By:JJTree: Do not edit this line. ASTOPENTAGATTR.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOPENTAGATTR extends SimpleNode {
  public ASTOPENTAGATTR(int id) {
    super(id);
  }

  public ASTOPENTAGATTR(Parse_xml p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Parse_xmlVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=54f8ce7e2308507ed0b54ddee7a1e994 (do not edit this line) */
