/* Generated By:JJTree: Do not edit this line. ASTOPENTAG.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOPENTAG extends SimpleNode {
  public ASTOPENTAG(int id) {
    super(id);
  }

  public ASTOPENTAG(Parse_xml p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Parse_xmlVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ea8dba252efed2624f423d179c35d333 (do not edit this line) */
