/* Generated By:JJTree: Do not edit this line. ASTPROGRAM.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPROGRAM extends SimpleNode {
  public ASTPROGRAM(int id) {
    super(id);
  }

  public ASTPROGRAM(Parse_xml p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Parse_xmlVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a294523bc8b47e90bdafb79ebdf75775 (do not edit this line) */
