/* Generated By:JavaCC: Do not edit this line. Parse_xmlTreeConstants.java Version 7.0.12 */
public interface Parse_xmlTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTOPENTAG = 1;
  public int JJTCLOSENTAG = 2;
  public int JJTE = 3;
  public int JJTID = 4;
  public int JJTIDNUM = 5;
  public int JJTAGENUM = 6;
  public int JJTNAME = 7;
  public int JJTPHONE = 8;
  public int JJTOPENTAGATTR = 9;
  public int JJTCLOSTAGATTR = 10;


  public String[] jjtNodeName = {
    "PROGRAM",
    "OPENTAG",
    "CLOSENTAG",
    "E",
    "ID",
    "IDNUM",
    "AGENUM",
    "Name",
    "PHONE",
    "OPENTAGATTR",
    "CLOSTAGATTR",
  };
}
/* JavaCC - OriginalChecksum=93df62e6711bb16e399d1385ce07ad8c (do not edit this line) */
