/* Generated By:JavaCC: Do not edit this line. Parse_xmlVisitor.java Version 7.0.12 */
public interface Parse_xmlVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTPROGRAM node, Object data);
  public Object visit(ASTOPENTAG node, Object data);
  public Object visit(ASTCLOSENTAG node, Object data);
  public Object visit(ASTE node, Object data);
  public Object visit(ASTID node, Object data);
  public Object visit(ASTIDNUM node, Object data);
  public Object visit(ASTAGENUM node, Object data);
  public Object visit(ASTName node, Object data);
  public Object visit(ASTPHONE node, Object data);
  public Object visit(ASTOPENTAGATTR node, Object data);
  public Object visit(ASTCLOSTAGATTR node, Object data);
}
/* JavaCC - OriginalChecksum=2e52636c53bd42f80d165c2490291486 (do not edit this line) */
