/* Generated By:JavaCC: Do not edit this line. Parse_xmlDefaultVisitor.java Version 7.0.12 */
public class Parse_xmlDefaultVisitor implements Parse_xmlVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPROGRAM node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOPENTAG node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCLOSENTAG node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTE node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTID node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIDNUM node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAGENUM node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTName node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPHONE node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTOPENTAGATTR node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCLOSTAGATTR node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=b9d1d3f0b3e60d292de3c4f408fd0b33 (do not edit this line) */
