/* Generated By:JJTree&JavaCC: Do not edit this line. Parse_xmlConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Parse_xmlConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SMALLER = 6;
  /** RegularExpression Id. */
  int GREATER = 7;
  /** RegularExpression Id. */
  int BACKSLASH = 8;
  /** RegularExpression Id. */
  int EQUEL = 9;
  /** RegularExpression Id. */
  int QUETE = 10;
  /** RegularExpression Id. */
  int IDATTR = 11;
  /** RegularExpression Id. */
  int NAMEATTR = 12;
  /** RegularExpression Id. */
  int PHONEATTR = 13;
  /** RegularExpression Id. */
  int AGEATTR = 14;
  /** RegularExpression Id. */
  int ID = 15;
  /** RegularExpression Id. */
  int NUM = 16;
  /** RegularExpression Id. */
  int PHONE = 17;
  /** RegularExpression Id. */
  int COMMA = 18;
  /** RegularExpression Id. */
  int SMALL = 19;
  /** RegularExpression Id. */
  int ALPHAID = 20;
  /** RegularExpression Id. */
  int DIGIT = 21;
  /** RegularExpression Id. */
  int DIGITONE = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"<\"",
    "\">\"",
    "\"/\"",
    "\"=\"",
    "\"\\\"\"",
    "\"id\"",
    "\"name\"",
    "\"phone\"",
    "\"age\"",
    "<ID>",
    "<NUM>",
    "<PHONE>",
    "\",\"",
    "\"</\"",
    "<ALPHAID>",
    "<DIGIT>",
    "<DIGITONE>",
  };

}
